### ISSUE TITLE
Merge multiple SEO component and remove hardcoded values.

### ISSUE THREAD

**Issue by yathomasi** [iterative/gatsby-theme-iterative#120] opened 2022-11-11 08:31 UTC
I see the source of the problem is we have hardcoded values in the DefaultSEO component.
https://github.com/iterative/gatsby-theme-iterative/blob/bc8ccef4109ae9ce994045b5518bd0dba0055336/packages/gatsby-theme-iterative/src/components/MainLayout/DefaultSEO/index.tsx#L102

I think we will want to merge [SEO component](https://github.com/iterative/gatsby-theme-iterative/blob/main/packages/gatsby-theme-iterative/src/components/SEO/index.tsx) and DefaultSEO component. I will creat a ticket for that and it can also cover the hardcoded values.

_Originally posted by @yathomasi in https://github.com/iterative/mlem.ai/issues/221#issuecomment-1311386351_

**Comment by rogermparent** [comment] 2022-11-14 13:31
Absolutely! We'll likely want to end up using Gatsby's `Head` API, but even going to a single `Helmet` component will be a big step along the way to reduce complexity.

**Comment by rogermparent** [comment] 2022-11-14 15:15
Part of this is a duplicate of #119, but this covers more so that one can be closed.

**Closed** 2022-11-28 16:06 UTC
Labels: good first issue, A: website, p2-nice-to-have
